// <auto-generated />
namespace Inforcauthu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d));
        
        string IMigrationMetadata.Id
        {
            get { return "202202221645280_d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
