// <auto-generated />
namespace Inforcauthu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ct));
        
        string IMigrationMetadata.Id
        {
            get { return "202202110900456_ct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
